	
// Code generated by sql2gorm. DO NOT EDIT.
package model


type MusicHistory struct {
	ID  int `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Mid int `gorm:"column:mid;NOT NULL"`
}

func (m *MusicHistory) TableName() string {
	return "music_history"
}
