	
// Code generated by sql2gorm. DO NOT EDIT.
// package model


// type MusicHistory struct {
// 	ID  int `gorm:"column:id;primary_key;AUTO_INCREMENT"`
// 	Mid int `gorm:"column:mid;NOT NULL"`
// }

// func (m *MusicHistory) TableName() string {
// 	return "music_history"
// }

package model


type MusicHistory struct {
	ID  int `gorm:"column:id;type:int(11);primary_key;AUTO_INCREMENT"`
	Eid int `gorm:"column:eid;type:int(11);NOT NULL"`
	Mid int `gorm:"column:mid;type:int(11);NOT NULL"`
}

func (m *MusicHistory) TableName() string {
	return "music_history"
}

