	
// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type User struct {
	Uid          int       `gorm:"column:uid;type:int(11);primary_key;AUTO_INCREMENT"`
	Name         string    `gorm:"column:name;type:varchar(100);NOT NULL"`
	Birthday     time.Time `gorm:"column:birthday;type:date"`
	Email        string    `gorm:"column:email;type:varchar(255);NOT NULL"`
	Password     string    `gorm:"column:password;type:varchar(255);NOT NULL"`
	ImageProfile string    `gorm:"column:image_profile;type:varchar(1000)"`
	GoogleID     string    `gorm:"column:google_id;type:varchar(100)"`
}

func (m *User) TableName() string {
	return "user"
}